### ISSUE TITLE
web3 connection in flutter throws error

### ISSUE THREAD

**Issue by ishwarchandratiwari** [simolus3/web3dart#31] opened 2019-03-28 09:42 UTC
E/flutter (22015): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)]
Unhandled Exception: SocketException: Failed host lookup:
'localhost:8545' (OS Error: No address associated with hostname, errno
= 7)

**Comment by simolus3** [comment] 2019-03-28 17:19
Closing as duplicate of #30

**Closed by simolus3** 2019-03-28 17:19 UTC
