### ISSUE TITLE
web3dart can not be used in angulardart or flutter web

### ISSUE THREAD

**Issue by timmornYE** [simolus3/web3dart#78] opened 2020-02-13 19:10 UTC
Will it be possible to make web3dart available in angulardart and flutter web?

**Comment by simolus3** [comment] 2020-02-13 19:47
Thanks for your interest. I'd say this is a duplicate of #74. Version `2.0.0-dev` on pub should have web support. 
I still need to do some more testing before I finally release it, but it's ready to be tried out.

**Closed by simolus3** 2020-02-13 19:47 UTC
